/**
 * UI Web Types Index
 * Central export for all TypeScript type definitions
 */

// Token Types
export type {
  DesignTokens,
  ColorTokens,
  SpacingTokens,
  TypographyTokens,
  BorderTokens,
  ShadowTokens,
  SemanticTokens,
  ThemeTokens,
  ComponentTokens,
  ColorTokenName,
  ColorTokenShade,
  SpacingTokenName,
  FontSizeName,
  FontWeightName,
  BorderRadiusName,
  ShadowName,
  TokenPath,
  TokenValue,
  ValidTokenPath,
  GetTokenValue,
  TokenAccessor,
} from './tokens';

// DaisyUI Types
export type {
  DaisyUITheme,
  DaisyUIColor,
  DaisyUISize,
  DaisyUIButtonVariants,
  DaisyUIButtonVariant,
  DaisyUIButtonSize,
  DaisyUIButtonShape,
  DaisyUIInputVariants,
  DaisyUIInputSize,
  DaisyUIInputState,
  DaisyUIInputVariant,
  DaisyUICardVariants,
  DaisyUICardElevation,
  DaisyUICardVariant,
  DaisyUIBadgeVariants,
  DaisyUIBadgeVariant,
  DaisyUIBadgeSize,
  DaisyUIAlertVariants,
  DaisyUIAlertVariant,
  DaisyUIModalVariants,
  DaisyUIModalSize,
  DaisyUIModalPosition,
  DaisyUIProgressVariants,
  DaisyUIProgressVariant,
  DaisyUIProgressSize,
  DaisyUILoadingVariants,
  DaisyUILoadingVariant,
  DaisyUILoadingSize,
  DaisyUICheckboxVariants,
  DaisyUICheckboxVariant,
  DaisyUICheckboxSize,
  DaisyUIRadioVariants,
  DaisyUIRadioVariant,
  DaisyUIRadioSize,
  DaisyUISelectVariants,
  DaisyUISelectVariant,
  DaisyUISelectSize,
  DaisyUISelectState,
  DaisyUITextareaVariants,
  DaisyUITextareaVariant,
  DaisyUITextareaSize,
  DaisyUITextareaState,
  DaisyUIToggleVariants,
  DaisyUIToggleVariant,
  DaisyUIToggleSize,
  DaisyUIRangeVariants,
  DaisyUIRangeVariant,
  DaisyUIRangeSize,
  DaisyUITooltipVariants,
  DaisyUITooltipPosition,
  DaisyUITooltipColor,
  DaisyUIDropdownVariants,
  DaisyUIDropdownPosition,
  DaisyUIMenuVariants,
  DaisyUIMenuSize,
  DaisyUIMenuVariant,
  DaisyUINavbarVariants,
  DaisyUINavbarSize,
  DaisyUIFooterVariants,
  DaisyUIFooterVariant,
  DaisyUIHeroVariants,
  DaisyUIHeroVariant,
  DaisyUIHeroSize,
  DaisyUIStatsVariants,
  DaisyUIStatsVariant,
  DaisyUIComponentProps,
  ValidDaisyUIVariant,
  DaisyUIThemeConfig,
  AllDaisyUIVariants,
} from './daisyui';

// Validation Types
export type {
  StrictComponentProps,
  ValidationResult,
  TokenValidationResult,
  ComponentValidationResult,
} from './validation';

// Validation Functions
export {
  isDaisyUITheme,
  isDaisyUIColor,
  isDaisyUISize,
  isDaisyUIButtonVariant,
  isDaisyUIButtonShape,
  isDaisyUIInputVariant,
  isDaisyUICardVariant,
  isColorTokenName,
  isSpacingTokenName,
  isFontSizeName,
  validateButtonProps,
  validateInputProps,
  validateCardProps,
  validateComponentProps,
  validateTokenAccess,
  createTypeSafeProps,
  generateDaisyUIClasses,
  DAISYUI_THEMES,
  DAISYUI_COLORS,
  DAISYUI_SIZES,
} from './validation';

// Re-export theme provider types for convenience
export type { DaisyUITheme as ThemeProviderTheme } from './daisyui';
