packages:
  - 'apps/*'
  - 'apps/smart-contracts/*'
  - 'packages/*'

# Catalog for shared dependencies
catalog:
  # Blockchain dependencies
  ethers: ^6.8.1
  hardhat: ^3.0.0
  "@openzeppelin/contracts": ^5.4.0
  "@solana/web3.js": ^1.98.4
  "@polkadot/api": ^16.4.4
  
  # Testing dependencies
  chai: ^5.3.1
  jest: ^30.0.5
  
  # Build tools
  typescript: ^5.9.2
  prettier: ^3.4.2
  turbo: ^2.5.6
