packages:
  - 'apps/*'
  - 'apps/smart-contracts/*'
  - 'packages/*'

# Catalog for shared dependencies
catalog:
  # Blockchain dependencies
  ethers: ^6.8.1
  hardhat: ^2.19.2
  "@openzeppelin/contracts": ^4.9.3
  "@solana/web3.js": ^1.87.6
  "@polkadot/api": ^10.11.2
  
  # Testing dependencies
  chai: ^4.3.10
  jest: ^29.7.0
  
  # Build tools
  typescript: ^5.3.3
  prettier: ^3.1.1
