import type { ThemeConfig, DaisyUITheme } from './types';

export const lightTheme: ThemeConfig = {
  name: 'light',
  displayName: 'Light',
  type: 'light',
  daisyUITheme: 'light',
  cssVars: {
    '--background': '0 0% 100%',
    '--foreground': '222.2 47.4% 11.2%',
    '--muted': '210 40% 96.1%',
    '--muted-foreground': '215.4 16.3% 46.9%',
    '--border': '214.3 31.8% 91.4%',
    '--input': '214.3 31.8% 91.4%',
    '--ring': '215 20.2% 65.1%',
    '--card': '0 0% 100%',
    '--card-foreground': '222.2 47.4% 11.2%',
    '--popover': '0 0% 100%',
    '--popover-foreground': '222.2 47.4% 11.2%',
    '--primary': '222 47% 11%',
    '--primary-foreground': '210 40% 96.1%',
    '--secondary': '210 40% 96%',
    '--secondary-foreground': '222.2 47.4% 11.2%',
    '--destructive': '0 84% 60%',
    '--destructive-foreground': '210 40% 98%',
    '--accent': '210 40% 96.1%',
    '--accent-foreground': '222.2 47.4% 11.2%',
    '--radius': '0.5rem',
  },
};

export const darkTheme: ThemeConfig = {
  name: 'dark',
  displayName: 'Dark',
  type: 'dark',
  daisyUITheme: 'dark',
  cssVars: {
    '--background': '222.2 84% 4.9%',
    '--foreground': '210 40% 98%',
    '--muted': '217.2 32.6% 17.5%',
    '--muted-foreground': '215 20.2% 65.1%',
    '--border': '217.2 32.6% 17.5%',
    '--input': '217.2 32.6% 17.5%',
    '--ring': '215 20.2% 65.1%',
    '--card': '222.2 84% 4.9%',
    '--card-foreground': '210 40% 98%',
    '--popover': '222.2 84% 4.9%',
    '--popover-foreground': '210 40% 98%',
    '--primary': '210 40% 98%',
    '--primary-foreground': '222.2 47.4% 11.2%',
    '--secondary': '217.2 32.6% 17.5%',
    '--secondary-foreground': '210 40% 98%',
    '--destructive': '0 62.8% 30.6%',
    '--destructive-foreground': '210 40% 98%',
    '--accent': '217.2 32.6% 17.5%',
    '--accent-foreground': '210 40% 98%',
    '--radius': '0.5rem',
  },
};

// DaisyUI theme configurations
export const daisyUIThemes: ThemeConfig[] = [
  { name: 'cupcake', displayName: 'Cupcake', type: 'light', daisyUITheme: 'cupcake' },
  { name: 'bumblebee', displayName: 'Bumblebee', type: 'light', daisyUITheme: 'bumblebee' },
  { name: 'emerald', displayName: 'Emerald', type: 'light', daisyUITheme: 'emerald' },
  { name: 'corporate', displayName: 'Corporate', type: 'light', daisyUITheme: 'corporate' },
  { name: 'synthwave', displayName: 'Synthwave', type: 'dark', daisyUITheme: 'synthwave' },
  { name: 'retro', displayName: 'Retro', type: 'light', daisyUITheme: 'retro' },
  { name: 'cyberpunk', displayName: 'Cyberpunk', type: 'dark', daisyUITheme: 'cyberpunk' },
  { name: 'valentine', displayName: 'Valentine', type: 'light', daisyUITheme: 'valentine' },
  { name: 'halloween', displayName: 'Halloween', type: 'dark', daisyUITheme: 'halloween' },
  { name: 'garden', displayName: 'Garden', type: 'light', daisyUITheme: 'garden' },
  { name: 'forest', displayName: 'Forest', type: 'dark', daisyUITheme: 'forest' },
  { name: 'aqua', displayName: 'Aqua', type: 'dark', daisyUITheme: 'aqua' },
  { name: 'lofi', displayName: 'Lo-Fi', type: 'light', daisyUITheme: 'lofi' },
  { name: 'pastel', displayName: 'Pastel', type: 'light', daisyUITheme: 'pastel' },
  { name: 'fantasy', displayName: 'Fantasy', type: 'light', daisyUITheme: 'fantasy' },
  { name: 'wireframe', displayName: 'Wireframe', type: 'light', daisyUITheme: 'wireframe' },
  { name: 'black', displayName: 'Black', type: 'dark', daisyUITheme: 'black' },
  { name: 'luxury', displayName: 'Luxury', type: 'dark', daisyUITheme: 'luxury' },
  { name: 'dracula', displayName: 'Dracula', type: 'dark', daisyUITheme: 'dracula' },
  { name: 'cmyk', displayName: 'CMYK', type: 'light', daisyUITheme: 'cmyk' },
  { name: 'autumn', displayName: 'Autumn', type: 'light', daisyUITheme: 'autumn' },
  { name: 'business', displayName: 'Business', type: 'light', daisyUITheme: 'business' },
  { name: 'acid', displayName: 'Acid', type: 'light', daisyUITheme: 'acid' },
  { name: 'lemonade', displayName: 'Lemonade', type: 'light', daisyUITheme: 'lemonade' },
  { name: 'night', displayName: 'Night', type: 'dark', daisyUITheme: 'night' },
  { name: 'coffee', displayName: 'Coffee', type: 'dark', daisyUITheme: 'coffee' },
  { name: 'winter', displayName: 'Winter', type: 'light', daisyUITheme: 'winter' },
  { name: 'dim', displayName: 'Dim', type: 'dark', daisyUITheme: 'dim' },
  { name: 'nord', displayName: 'Nord', type: 'light', daisyUITheme: 'nord' },
  { name: 'sunset', displayName: 'Sunset', type: 'dark', daisyUITheme: 'sunset' },
];

export const defaultThemes: ThemeConfig[] = [lightTheme, darkTheme, ...daisyUIThemes];

// Helper function to get DaisyUI themes list
export const getDaisyUIThemeNames = (): DaisyUITheme[] => [
  'light',
  'dark',
  'cupcake',
  'bumblebee',
  'emerald',
  'corporate',
  'synthwave',
  'retro',
  'cyberpunk',
  'valentine',
  'halloween',
  'garden',
  'forest',
  'aqua',
  'lofi',
  'pastel',
  'fantasy',
  'wireframe',
  'black',
  'luxury',
  'dracula',
  'cmyk',
  'autumn',
  'business',
  'acid',
  'lemonade',
  'night',
  'coffee',
  'winter',
  'dim',
  'nord',
  'sunset',
];
