const StyleDictionary = require('style-dictionary').default;

// Custom transforms for DaisyUI compatibility
StyleDictionary.registerTransform({
  name: 'size/px',
  type: 'value',
  filter: token => token.attributes?.category === 'size' || token.attributes?.category === 'space',
  transform: token => {
    try {
      if (typeof token.original.value === 'string' && token.original.value.includes('rem')) {
        return token.original.value;
      }
      return parseFloat(token.original.value) + 'px';
    } catch (error) {
      console.error(`Error transforming token ${token.name}:`, error);
      return token.original.value;
    }
  },
});

StyleDictionary.registerTransform({
  name: 'color/hex',
  type: 'value',
  filter: token => token.attributes?.category === 'color',
  transform: token => token.original.value,
});

// Custom filter for Tailwind-compatible tokens
StyleDictionary.registerFilter({
  name: 'tailwind-compatible',
  filter: token => {
    return ['color', 'size', 'space', 'fontFamily', 'fontSize', 'borderRadius', 'boxShadow', 'fontWeight'].includes(token.attributes?.category);
  },
});

// Custom format for TypeScript declarations
StyleDictionary.registerFormat({
  name: 'typescript/es6-declarations',
  format: function(dictionary) {
    const tokens = dictionary.allTokens;
    
    // Group tokens by category
    const tokensByCategory = tokens.reduce((acc, token) => {
      const category = token.attributes.category;
      if (!acc[category]) acc[category] = {};
      
      // Handle nested tokens (e.g., primary.500)
      const path = token.path.slice(1); // Remove category from path
      let current = acc[category];
      
      for (let i = 0; i < path.length - 1; i++) {
        if (!current[path[i]]) current[path[i]] = {};
        current = current[path[i]];
      }
      
      current[path[path.length - 1]] = token.value;
      return acc;
    }, {});

    let output = '// Generated by Style Dictionary\n\n';
    
    // Generate interfaces for each category
    Object.keys(tokensByCategory).forEach(category => {
      const categoryName = category.charAt(0).toUpperCase() + category.slice(1);
      output += `export interface ${categoryName}Tokens {\n`;
      output += generateInterface(tokensByCategory[category], 2);
      output += '}\n\n';
    });

    // Generate main DesignTokens interface
    output += 'export interface DesignTokens {\n';
    Object.keys(tokensByCategory).forEach(category => {
      const categoryName = category.charAt(0).toUpperCase() + category.slice(1);
      output += `  ${category}: ${categoryName}Tokens;\n`;
    });
    output += '}\n\n';

    // Generate DaisyUI types
    output += `export type DaisyUISize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';\n`;
    output += `export type DaisyUIColor = 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';\n`;
    output += `export type DaisyUITheme = 'light' | 'dark' | 'cupcake' | 'bumblebee' | 'emerald' | 'corporate' | 'synthwave' | 'retro' | 'cyberpunk' | 'valentine' | 'halloween' | 'garden' | 'forest' | 'aqua' | 'lofi' | 'pastel' | 'fantasy' | 'wireframe' | 'black' | 'luxury' | 'dracula' | 'cmyk' | 'autumn' | 'business' | 'acid' | 'lemonade' | 'night' | 'coffee' | 'winter' | 'dim' | 'nord' | 'sunset' | 'todo-light' | 'todo-dark';\n\n`;

    // Generate component prop interfaces
    output += `export interface DaisyUIComponentProps {\n`;
    output += `  size?: DaisyUISize;\n`;
    output += `  color?: DaisyUIColor;\n`;
    output += `  disabled?: boolean;\n`;
    output += `  loading?: boolean;\n`;
    output += `}\n\n`;

    output += `export interface ButtonProps extends DaisyUIComponentProps {\n`;
    output += `  outline?: boolean;\n`;
    output += `  ghost?: boolean;\n`;
    output += `  link?: boolean;\n`;
    output += `  block?: boolean;\n`;
    output += `  wide?: boolean;\n`;
    output += `  square?: boolean;\n`;
    output += `  circle?: boolean;\n`;
    output += `}\n\n`;

    output += `export interface InputProps extends DaisyUIComponentProps {\n`;
    output += `  bordered?: boolean;\n`;
    output += `  ghost?: boolean;\n`;
    output += `  error?: boolean;\n`;
    output += `}\n`;

    return output;
  }
});

// Custom format for DaisyUI theme configuration
StyleDictionary.registerFormat({
  name: 'javascript/daisyui-themes',
  format: function(dictionary) {
    const tokens = dictionary.allTokens;
    
    // Filter semantic color tokens
    const semanticTokens = tokens.filter(token => 
      token.path[0] === 'semantic' && token.path[1] === 'color'
    );

    const themes = {};
    
    semanticTokens.forEach(token => {
      const themeName = token.path[2]; // light or dark
      const colorKey = token.path.slice(3).join('-'); // primary, primary-focus, etc.
      
      if (!themes[`todo-${themeName}`]) {
        themes[`todo-${themeName}`] = {};
      }
      
      themes[`todo-${themeName}`][colorKey] = token.value;
    });

    return `// Generated DaisyUI theme configuration
module.exports = ${JSON.stringify(themes, null, 2)};`;
  }
});

function generateInterface(obj, indent = 0) {
  let output = '';
  const spaces = ' '.repeat(indent);
  
  Object.keys(obj).forEach(key => {
    if (typeof obj[key] === 'object' && obj[key] !== null && !Array.isArray(obj[key])) {
      output += `${spaces}${key}: {\n`;
      output += generateInterface(obj[key], indent + 2);
      output += `${spaces}};\n`;
    } else {
      output += `${spaces}${key}: string;\n`;
    }
  });
  
  return output;
}

// Build configuration
const config = {
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/tokens/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    js: {
      transformGroup: 'js',
      buildPath: 'dist/tokens/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
        },
        {
          destination: 'tokens.d.ts',
          format: 'typescript/es6-declarations',
        },
      ],
    },
    tailwind: {
      transformGroup: 'js',
      buildPath: 'dist/tokens/',
      files: [
        {
          destination: 'tailwind-tokens.js',
          format: 'javascript/object',
          filter: 'tailwind-compatible',
        },
      ],
    },
    daisyui: {
      transformGroup: 'js',
      buildPath: 'dist/tokens/',
      files: [
        {
          destination: 'daisyui-themes.js',
          format: 'javascript/daisyui-themes',
        },
      ],
    },
  },
};

// Build the tokens
async function buildTokens() {
  try {
    const sd = new StyleDictionary(config);
    await sd.buildAllPlatforms();
    console.log('✅ Style Dictionary build completed successfully');
  } catch (error) {
    console.error('❌ Style Dictionary build failed:', error.message);
    process.exit(1);
  }
}

buildTokens();
