apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: todo-app
type: Opaque
data:
  # Base64 encoded placeholder values - replace with actual values in production
  uri: bW9uZ29kYjovL3VzZXJuYW1lOnBhc3N3b3JkQG1vbmdvZGI6MjcwMTcvdG9kb19kYg==  # mongodb://username:password@mongodb:27017/todo_db
