apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secrets
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: todo-monorepo
type: Opaque
data:
  # MongoDB credentials (base64 encoded)
  MONGODB_USERNAME: YWRtaW4=  # admin
  MONGODB_PASSWORD: cGFzc3dvcmQ=  # password
  MONGODB_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy90b2RvLWFwcD9hdXRoU291cmNlPWFkbWlu  # mongodb://admin:password@mongodb-service:27017/todo-app?authSource=admin
  
  # Redis password (if needed)
  REDIS_PASSWORD: ""
  REDIS_URI: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzk=  # redis://redis-service:6379
  
  # JWT Secret
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==  # your-jwt-secret-key-change-in-production
  
  # Database encryption key
  DB_ENCRYPTION_KEY: eW91ci1kYi1lbmNyeXB0aW9uLWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==  # your-db-encryption-key-change-in-production

---
apiVersion: v1
kind: Secret
metadata:
  name: blockchain-secrets
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/component: blockchain-secrets
    app.kubernetes.io/part-of: todo-monorepo
type: Opaque
data:
  # Blockchain network configurations (base64 encoded)
  POLYGON_RPC_URL: aHR0cHM6Ly9wb2x5Z29uLXJwYy5jb20=  # https://polygon-rpc.com
  POLYGON_PRIVATE_KEY: eW91ci1wb2x5Z29uLXByaXZhdGUta2V5  # your-polygon-private-key
  
  SOLANA_RPC_URL: aHR0cHM6Ly9hcGkubWFpbm5ldC1iZXRhLnNvbGFuYS5jb20=  # https://api.mainnet-beta.solana.com
  SOLANA_PRIVATE_KEY: eW91ci1zb2xhbmEtcHJpdmF0ZS1rZXk=  # your-solana-private-key
  
  POLKADOT_RPC_URL: d3NzOi8vcnBjLnBvbGthZG90LmlvLw==  # wss://rpc.polkadot.io/
  POLKADOT_PRIVATE_KEY: eW91ci1wb2xrYWRvdC1wcml2YXRlLWtleQ==  # your-polkadot-private-key
  
  MOONBEAM_RPC_URL: aHR0cHM6Ly9ycGMuYXBpLm1vb25iZWFtLm5ldHdvcms=  # https://rpc.api.moonbeam.network
  MOONBEAM_PRIVATE_KEY: eW91ci1tb29uYmVhbS1wcml2YXRlLWtleQ==  # your-moonbeam-private-key
  MOONBEAM_API_KEY: eW91ci1tb29uYmVhbS1hcGkta2V5  # your-moonbeam-api-key
  
  BASE_RPC_URL: aHR0cHM6Ly9tYWlubmV0LmJhc2Uub3Jn  # https://mainnet.base.org
  BASE_PRIVATE_KEY: eW91ci1iYXNlLXByaXZhdGUta2V5  # your-base-private-key
  BASESCAN_API_KEY: eW91ci1iYXNlc2Nhbi1hcGkta2V5  # your-basescan-api-key

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/component: tls
    app.kubernetes.io/part-of: todo-monorepo
type: kubernetes.io/tls
data:
  # TLS certificate and key (base64 encoded)
  # Replace with your actual certificate and key
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...