import { type GatewayRoute } from '../types/route';

const defaultTimeoutMs = 10_000;

export const routeTable = [
  {
    id: 'gateway.index',
    publicPath: '/api/v1',
    methods: ['GET'],
    upstream: 'gateway',
    auth: 'public',
    timeoutMs: 1_000,
    retries: 0,
    tags: ['gateway'],
    owner: 'gateway',
    openapi: {
      source: 'gateway',
      operationId: 'gatewayIndex',
      summary: 'Get gateway service metadata',
      responseShape: 'GatewayMetadata',
    },
  },
  {
    id: 'gateway.health',
    publicPath: '/api/v1/health',
    methods: ['GET'],
    upstream: 'gateway',
    auth: 'public',
    timeoutMs: 2_000,
    retries: 0,
    tags: ['health'],
    owner: 'gateway',
    openapi: {
      source: 'gateway',
      operationId: 'gatewayHealth',
      summary: 'Get gateway health metadata',
      responseShape: 'GatewayMetadata',
    },
  },
  {
    id: 'gateway.health.ready',
    publicPath: '/api/v1/health/ready',
    methods: ['GET'],
    upstream: 'gateway',
    auth: 'public',
    timeoutMs: 2_000,
    retries: 0,
    tags: ['health'],
    owner: 'gateway',
    openapi: {
      source: 'gateway',
      operationId: 'gatewayHealthReady',
      summary: 'Get gateway readiness status',
      responseShape: 'GatewayReadiness',
    },
  },
  {
    id: 'auth.register',
    publicPath: '/api/v1/auth/register',
    methods: ['POST'],
    upstream: 'bun-api',
    upstreamPath: '/api/v1/auth/register',
    auth: 'public',
    timeoutMs: defaultTimeoutMs,
    retries: 0,
    tags: ['auth'],
    owner: 'api-bun',
    openapi: {
      source: 'bun-openapi',
      operationId: 'registerUser',
      summary: 'Register a user',
      responseShape: 'AuthResponse',
    },
  },
  {
    id: 'auth.login',
    publicPath: '/api/v1/auth/login',
    methods: ['POST'],
    upstream: 'bun-api',
    upstreamPath: '/api/v1/auth/login',
    auth: 'public',
    timeoutMs: defaultTimeoutMs,
    retries: 0,
    tags: ['auth'],
    owner: 'api-bun',
    openapi: {
      source: 'bun-openapi',
      operationId: 'loginUser',
      summary: 'Log in a user',
      responseShape: 'AuthResponse',
    },
  },
  {
    id: 'auth.refresh',
    publicPath: '/api/v1/auth/refresh',
    methods: ['POST'],
    upstream: 'bun-api',
    upstreamPath: '/api/v1/auth/refresh',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 0,
    tags: ['auth'],
    owner: 'api-bun',
    openapi: {
      source: 'bun-openapi',
      operationId: 'refreshAuthToken',
      summary: 'Refresh an access token',
      responseShape: 'AuthResponse',
    },
  },
  {
    id: 'auth.profile',
    publicPath: '/api/v1/auth/profile',
    methods: ['GET'],
    upstream: 'bun-api',
    upstreamPath: '/api/v1/auth/profile',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 1,
    fallback: 'nest-api',
    tags: ['auth'],
    owner: 'api-bun',
    openapi: {
      source: 'bun-openapi',
      operationId: 'getAuthProfile',
      summary: 'Get the current authenticated user profile',
      responseShape: 'PublicUser',
    },
  },
  {
    id: 'users.profile',
    publicPath: '/api/v1/users/profile',
    methods: ['GET'],
    upstream: 'nest-api',
    upstreamPath: '/api/v1/users/profile',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 1,
    tags: ['users'],
    owner: 'api',
    openapi: {
      source: 'nest-openapi',
      operationId: 'getUserProfile',
      summary: 'Get the current user profile',
      responseShape: 'UserProfile',
    },
  },
  {
    id: 'todos.list',
    publicPath: '/api/v1/todos',
    methods: ['GET'],
    upstream: 'bun-api',
    upstreamPath: '/api/v1/todos',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 1,
    fallback: 'nest-api',
    tags: ['todos'],
    owner: 'api-bun',
    openapi: {
      source: 'bun-openapi',
      operationId: 'listTodos',
      summary: 'List todos with filtering and pagination',
      responseShape: 'PaginatedTodos',
    },
  },
  {
    id: 'todos.create',
    publicPath: '/api/v1/todos',
    methods: ['POST'],
    upstream: 'nest-api',
    upstreamPath: '/api/v1/todos',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 0,
    tags: ['todos'],
    owner: 'api',
    openapi: {
      source: 'nest-openapi',
      operationId: 'createTodo',
      summary: 'Create a todo',
      responseShape: 'ApiTodo',
    },
  },
  {
    id: 'todos.stats',
    publicPath: '/api/v1/todos/stats',
    methods: ['GET'],
    upstream: 'bun-api',
    upstreamPath: '/api/v1/todos/stats',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 1,
    fallback: 'nest-api',
    tags: ['todos'],
    owner: 'api-bun',
    openapi: {
      source: 'bun-openapi',
      operationId: 'getTodoStats',
      summary: 'Get todo statistics',
      responseShape: 'TodoStats',
    },
  },
  {
    id: 'todos.by-id',
    publicPath: '/api/v1/todos/:id',
    methods: ['GET', 'PATCH', 'DELETE'],
    upstream: 'nest-api',
    upstreamPath: '/api/v1/todos/:id',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 0,
    tags: ['todos'],
    owner: 'api',
    openapi: {
      source: 'nest-openapi',
      operationId: 'getUpdateOrDeleteTodoById',
      summary: 'Get, update, or delete a todo by ID',
      responseShape: 'ApiTodo',
    },
  },
  {
    id: 'todos.toggle',
    publicPath: '/api/v1/todos/:id/toggle',
    methods: ['PATCH'],
    upstream: 'nest-api',
    upstreamPath: '/api/v1/todos/:id/toggle',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 0,
    tags: ['todos'],
    owner: 'api',
    openapi: {
      source: 'nest-openapi',
      operationId: 'toggleTodo',
      summary: 'Toggle a todo completion state',
      responseShape: 'ApiTodo',
    },
  },
] satisfies GatewayRoute[];
