import { type GatewayRoute } from '../types/route';

const defaultTimeoutMs = 10_000;

export const routeTable = [
  {
    id: 'gateway.index',
    publicPath: '/api/v1',
    methods: ['GET'],
    upstream: 'gateway',
    auth: 'public',
    timeoutMs: 1_000,
    retries: 0,
    tags: ['gateway'],
    owner: 'gateway',
  },
  {
    id: 'gateway.health',
    publicPath: '/api/v1/health',
    methods: ['GET'],
    upstream: 'gateway',
    auth: 'public',
    timeoutMs: 2_000,
    retries: 0,
    tags: ['health'],
    owner: 'gateway',
  },
  {
    id: 'gateway.health.ready',
    publicPath: '/api/v1/health/ready',
    methods: ['GET'],
    upstream: 'gateway',
    auth: 'public',
    timeoutMs: 2_000,
    retries: 0,
    tags: ['health'],
    owner: 'gateway',
  },
  {
    id: 'auth.register',
    publicPath: '/api/v1/auth/register',
    methods: ['POST'],
    upstream: 'bun-api',
    upstreamPath: '/api/v1/auth/register',
    auth: 'public',
    timeoutMs: defaultTimeoutMs,
    retries: 0,
    tags: ['auth'],
    owner: 'api-bun',
  },
  {
    id: 'auth.login',
    publicPath: '/api/v1/auth/login',
    methods: ['POST'],
    upstream: 'bun-api',
    upstreamPath: '/api/v1/auth/login',
    auth: 'public',
    timeoutMs: defaultTimeoutMs,
    retries: 0,
    tags: ['auth'],
    owner: 'api-bun',
  },
  {
    id: 'auth.refresh',
    publicPath: '/api/v1/auth/refresh',
    methods: ['POST'],
    upstream: 'bun-api',
    upstreamPath: '/api/v1/auth/refresh',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 0,
    tags: ['auth'],
    owner: 'api-bun',
  },
  {
    id: 'auth.profile',
    publicPath: '/api/v1/auth/profile',
    methods: ['GET'],
    upstream: 'bun-api',
    upstreamPath: '/api/v1/auth/profile',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 1,
    fallback: 'nest-api',
    tags: ['auth'],
    owner: 'api-bun',
  },
  {
    id: 'users.profile',
    publicPath: '/api/v1/users/profile',
    methods: ['GET'],
    upstream: 'nest-api',
    upstreamPath: '/api/v1/users/profile',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 1,
    tags: ['users'],
    owner: 'api',
  },
  {
    id: 'todos.list',
    publicPath: '/api/v1/todos',
    methods: ['GET'],
    upstream: 'bun-api',
    upstreamPath: '/api/v1/todos',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 1,
    fallback: 'nest-api',
    tags: ['todos'],
    owner: 'api-bun',
  },
  {
    id: 'todos.create',
    publicPath: '/api/v1/todos',
    methods: ['POST'],
    upstream: 'nest-api',
    upstreamPath: '/api/v1/todos',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 0,
    tags: ['todos'],
    owner: 'api',
  },
  {
    id: 'todos.stats',
    publicPath: '/api/v1/todos/stats',
    methods: ['GET'],
    upstream: 'bun-api',
    upstreamPath: '/api/v1/todos/stats',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 1,
    fallback: 'nest-api',
    tags: ['todos'],
    owner: 'api-bun',
  },
  {
    id: 'todos.by-id',
    publicPath: '/api/v1/todos/:id',
    methods: ['GET', 'PATCH', 'PUT', 'DELETE'],
    upstream: 'nest-api',
    upstreamPath: '/api/v1/todos/:id',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 0,
    tags: ['todos'],
    owner: 'api',
  },
  {
    id: 'todos.toggle',
    publicPath: '/api/v1/todos/:id/toggle',
    methods: ['PATCH'],
    upstream: 'nest-api',
    upstreamPath: '/api/v1/todos/:id/toggle',
    auth: 'required',
    timeoutMs: defaultTimeoutMs,
    retries: 0,
    tags: ['todos'],
    owner: 'api',
  },
] satisfies GatewayRoute[];
