import type { Todo } from '@/components/TodoItem';
import { BlockchainNetwork } from '@todo/services';

export const sampleTodos: Todo[] = [
  {
    id: '1',
    title: 'Set up blockchain wallet',
    description: 'Connect MetaMask or other Web3 wallet for blockchain functionality',
    completed: false,
    priority: 'high',
    dueDate: new Date('2024-01-15'),
    tags: ['blockchain', 'setup'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
    userId: 'user-1',
  },
  {
    id: '2',
    title: 'Complete project documentation',
    description: 'Write comprehensive documentation for the todo application',
    completed: true,
    priority: 'medium',
    tags: ['documentation', 'project'],
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-12'),
    userId: 'user-1',
    blockchainNetwork: BlockchainNetwork.SOLANA,
    transactionHash: '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
    blockchainAddress: 'solana-address-2',
  },
  {
    id: '3',
    title: 'Review code changes',
    description: 'Review and approve pending pull requests',
    completed: false,
    priority: 'medium',
    dueDate: new Date('2024-01-20'),
    tags: ['code-review', 'development'],
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-09'),
    userId: 'user-1',
  },
  {
    id: '4',
    title: 'Deploy to production',
    description: 'Deploy the application to production environment',
    completed: false,
    priority: 'high',
    tags: ['deployment', 'production'],
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
    userId: 'user-1',
    blockchainNetwork: BlockchainNetwork.POLYGON,
    transactionHash: '0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890',
    blockchainAddress: 'polygon-address-4',
  },
  {
    id: '5',
    title: 'Update dependencies',
    description: 'Update all npm packages to their latest versions',
    completed: false,
    priority: 'low',
    tags: ['maintenance', 'dependencies'],
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-07'),
    userId: 'user-1',
  },
];
